version: "3.8"
services:
  app:
    build: .
    command: python travel_app.py
    depends_on:
    - db
    links:
    - db
    ports:
      - "8001:8001"
    volumes:
      - .:/python-flask
  db:
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
