version: "3.8"
services:
  app:
    build: .
    command: python user_app.py
    depends_on:
    - db
    links:
    - db
    ports:
      - "8000:8000"
    volumes:
      - .:/python-flask
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
